replicaCount: 1
image:
  registry:
  group:
  repository:
  pullPolicy: IfNotPresent
  tag:
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: kong
  annotations:
    konghq.com/strip-path: "true"
  hosts:
    - host: ""
      paths:
        - path: /lifestyle-api
          pathType: Prefix
  tls: []
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources: {}
livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}


